sudo: false
language: python
python:
        - 2.7
        - 3.3
        - 3.4
install:
        - if [[ $TRAVIS_PYTHON_VERSION != 3.4 ]]; then pip install -r requirements-2.7.txt; fi
        - pip install -r requirements.txt
        - pip install -r requirements-test.txt
        - pip install python-coveralls
        - pip install spinnaker_proxy
before_script:
        - spinnaker_proxy.py -qct cspc276.cs.man.ac.uk &
        - export SPINNAKER_PROXY_PID=$!
script: py.test rig docs --spinn5 --spinnaker localhost 8 8 --bmp spinn-4c.cs.man.ac.uk --cov rig --durations=10
after_success:
        - coveralls
after_script:
        - kill $SPINNAKER_PROXY_PID
        - sleep 0.5
        - kill -9 $SPINNAKER_PROXY_PID
notifications:
        email: false
