sudo: false
language: python
python:
        - 2.7
        - 3.3
        - 3.4
install:
        - python setup.py install
        - pip install -r requirements-test.txt
        - pip install python-coveralls
        - pip install spinnaker_proxy
before_script:
        - spinnaker_proxy.py -qct cspc276.cs.man.ac.uk &
        - export SPINNAKER_PROXY_PID=$!
script:
        # Run the main test suite against real hardware and against the
        # installed codebase.
        - py.test tests/ --spinn5 --spinnaker localhost 8 8 --bmp spinn-4c.cs.man.ac.uk --cov rig --cov tests --durations=10
        # Run doctests in code
        - py.test rig/
        # Run doctests in documentation
        - py.test docs/
        # Code quality check
        - flake8 rig
after_success:
        - coveralls
after_script:
        - kill $SPINNAKER_PROXY_PID
        - sleep 0.5
        - kill -9 $SPINNAKER_PROXY_PID
notifications:
        email: false

matrix:
    fast_finish: true
