sudo: false
language: python
python:
        - 2.7
        - 3.3
        - 3.4
install:
        - if [[ $TRAVIS_PYTHON_VERSION != 3.4 ]]; then pip install -r requirements-2.7.txt; fi
        - pip install -r requirements.txt
        - pip install -r requirements-test.txt
        - pip install python-coveralls
script: py.test rig docs --no-boot --spinn5 --spinnaker spinn-4.cs.man.ac.uk 8 8 --bmp spinn-4c.cs.man.ac.uk --cov rig
after_success:
        - coveralls
notifications:
        email: false
