sudo: false
language: python
python:
        - 2.7
        - 3.4
        - 3.5
install:
        - python setup.py install
        - pip install -r requirements-test.txt
        - pip install codecov
script:
        # Run the main test suite against real hardware and against the
        # installed codebase. Note: since we're testing an installed version,
        # the code coverage must be checked against this version, not the one in
        # './rig/'.
        - >
            py.test tests/ \
                    --spinnaker spinn-4.cs.man.ac.uk --spinn5 \
                    --bmp spinn-4c.cs.man.ac.uk \
                    --cov "$(./utils/rig_path.py)" \
                    --cov tests \
                    --durations=10
        # Run doctests in code
        - py.test rig/ --doctest-modules -p no:warnings
        # Run doctests in documentation
        - py.test docs/ --doctest-glob='*_doctest.rst'
        # Code quality check
        - flake8 rig tests
after_success:
        - codecov
notifications:
        email: false

matrix:
    fast_finish: true
