sudo: false
language: python
python:
        - 2.7
        - 3.3
        - 3.4
install:
        - if [[ $TRAVIS_PYTHON_VERSION != 3.4 ]]; then pip install -r requirements-2.7.txt; fi
        - pip install -r requirements.txt
        - pip install -r requirements-test.txt
        - pip install python-coveralls
before_script:
        - export MY_MAGIC="magic"
script: py.test rig docs --cov rig
after_success:
        - coveralls
after_script:
        - if [ -n "$MY_MAGIC" ]; then echo "Env survived!"; else echo "Env missing."; fi
notifications:
        email: false
